### ISSUE TITLE
Use config package to store credentials

### ISSUE THREAD

**Issue by chrowe** [cloudyr/aws.s3#240]
Please specify whether your issue is about:
 - [ ] a possible bug
 - [x] a question about package functionality
 - [x] a suggested code or documentation change, improvement to the code, or feature request

Is it possible to retrieve S3 credentials using the [config package](https://cran.r-project.org/web/packages/config/vignettes/introduction.html) instead of environment variables without have to specify them every time?

Put your code here:
I know that I can set them inline like this...
config.yml
```yml
default:
  s3:
    bucket: 'my_bucket'
    key: YOUR_AWS_ACCESS_KEY
    secret: YOUR_AWS_SECRET_ACCESS_KEY
```

R code
```R
s3conf <- config::get("s3")
get_bucket(
  bucket = s3conf$bucket,
  key =  s3conf$key,
  secret =  s3conf$secret
) 
```

But it would be nice to be able to just set that once like you can with Sys.setenv
